In [11]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Model(nn.Module):
    def __init__(self):
        super().__init__()  # nn.Module이 가지고 있는 모든 init 가져오기
        self._is_full_backward_hook
        self.conv1 = nn.Conv2d(1, 20, 5)
        self.conv2 = nn.Conv2d(20, 20, 5)
        self.num_features = torch.zeros(10)
        self.number = torch.ones(5)
        self.register_buffer("num_feature", self.num_features)  # buffer에 데이터 할당

    def forward(self, x):
        x = F.relu(self.conv1(x))
        return F.relu(self.conv2(x))

In [12]:
model = Model()

In [13]:
print(model._is_full_backward_hook)

None


In [14]:
print(model.num_feature.device)
print(model.number.device)

cpu
cpu


In [15]:
model.cuda()    # buffer에 넣은 데이터만 gpu로 넘어감
print(model.num_feature.device)
print(model.number.device)

cuda:0
cpu


In [16]:
model.state_dict()

OrderedDict([('num_feature',
              tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], device='cuda:0')),
             ('conv1.weight',
              tensor([[[[-0.1173,  0.1697, -0.1032, -0.0558,  0.0140],
                        [-0.0136, -0.0585, -0.0521,  0.0039, -0.0569],
                        [ 0.1941, -0.0411,  0.0510, -0.0190, -0.1193],
                        [-0.0230, -0.1750, -0.0455,  0.1837, -0.0652],
                        [-0.0184,  0.1336, -0.0893,  0.0563,  0.1299]]],
              
              
                      [[[ 0.0538, -0.0281, -0.0299, -0.0359, -0.1776],
                        [ 0.0832, -0.0700,  0.1188,  0.0014, -0.1466],
                        [-0.0032,  0.1386, -0.1173,  0.0715,  0.0632],
                        [ 0.0994,  0.0571, -0.0442, -0.1151,  0.1601],
                        [ 0.0817, -0.1822, -0.0610, -0.0254, -0.1065]]],
              
              
                      [[[ 0.0501,  0.1214,  0.0904,  0.0520,  0.0958],
              

In [20]:
layer = nn.Conv2d(in_channels=3, out_channels=6, kernel_size=(3,3),padding=1)

model.add_module('layer1', layer)   # 기존 Model에 Module 추가

model

Model(
  (conv1): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(20, 20, kernel_size=(5, 5), stride=(1, 1))
  (layer1): Conv2d(3, 6, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
)

In [26]:
model.get_submodule("conv1")    # submodule 반환

Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))

In [31]:
model.get_parameter('conv1.weight')  # parameter 값에 접근

Parameter containing:
tensor([[[[-0.1173,  0.1697, -0.1032, -0.0558,  0.0140],
          [-0.0136, -0.0585, -0.0521,  0.0039, -0.0569],
          [ 0.1941, -0.0411,  0.0510, -0.0190, -0.1193],
          [-0.0230, -0.1750, -0.0455,  0.1837, -0.0652],
          [-0.0184,  0.1336, -0.0893,  0.0563,  0.1299]]],


        [[[ 0.0538, -0.0281, -0.0299, -0.0359, -0.1776],
          [ 0.0832, -0.0700,  0.1188,  0.0014, -0.1466],
          [-0.0032,  0.1386, -0.1173,  0.0715,  0.0632],
          [ 0.0994,  0.0571, -0.0442, -0.1151,  0.1601],
          [ 0.0817, -0.1822, -0.0610, -0.0254, -0.1065]]],


        [[[ 0.0501,  0.1214,  0.0904,  0.0520,  0.0958],
          [ 0.0218,  0.1796, -0.1540, -0.0337,  0.1694],
          [ 0.0393,  0.0115, -0.1027,  0.1924, -0.0563],
          [ 0.0520, -0.1809, -0.1296,  0.1658, -0.1715],
          [ 0.1849, -0.0940,  0.1015,  0.0133, -0.0957]]],


        [[[ 0.1463,  0.0280, -0.0731,  0.0677,  0.1113],
          [-0.1679, -0.1710,  0.1989,  0.1669,  0.0066

In [38]:
for name, param in model.named_parameters():
    print(name, param.shape)

conv1.weight torch.Size([20, 1, 5, 5])
conv1.bias torch.Size([20])
conv2.weight torch.Size([20, 20, 5, 5])
conv2.bias torch.Size([20])
layer1.weight torch.Size([6, 3, 3, 3])
layer1.bias torch.Size([6])


In [32]:
model.get_parameter('conv1.bias')   # parameter 값에 접근

Parameter containing:
tensor([-0.0341,  0.0767,  0.1958,  0.1967, -0.1290, -0.1438,  0.0267,  0.0673,
         0.0141,  0.1113, -0.1448,  0.1844,  0.0934, -0.0854, -0.0986, -0.0311,
        -0.0542,  0.0905,  0.1887, -0.1135], device='cuda:0',
       requires_grad=True)

In [40]:
model.get_buffer('num_feature') # buffer 값 접근

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], device='cuda:0')

In [47]:
@torch.no_grad()

def init_weights(m):
    print(m)
    if type(m) == nn.Linear:
        m.weight.fill_(1.0)
        print(m.weight)
net = nn.Sequential(nn.Linear(2, 2), 
                    nn.Linear(2, 2))
net.apply(init_weights) # init_weights 함수를 net에 모두 적용

Linear(in_features=2, out_features=2, bias=True)
Parameter containing:
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
Linear(in_features=2, out_features=2, bias=True)
Parameter containing:
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
)


Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
)

In [50]:
model.state_dict()

OrderedDict([('num_feature',
              tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], device='cuda:0')),
             ('conv1.weight',
              tensor([[[[-0.1173,  0.1697, -0.1032, -0.0558,  0.0140],
                        [-0.0136, -0.0585, -0.0521,  0.0039, -0.0569],
                        [ 0.1941, -0.0411,  0.0510, -0.0190, -0.1193],
                        [-0.0230, -0.1750, -0.0455,  0.1837, -0.0652],
                        [-0.0184,  0.1336, -0.0893,  0.0563,  0.1299]]],
              
              
                      [[[ 0.0538, -0.0281, -0.0299, -0.0359, -0.1776],
                        [ 0.0832, -0.0700,  0.1188,  0.0014, -0.1466],
                        [-0.0032,  0.1386, -0.1173,  0.0715,  0.0632],
                        [ 0.0994,  0.0571, -0.0442, -0.1151,  0.1601],
                        [ 0.0817, -0.1822, -0.0610, -0.0254, -0.1065]]],
              
              
                      [[[ 0.0501,  0.1214,  0.0904,  0.0520,  0.0958],
              

In [51]:
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[[[-0.1173,  0.1697, -0.1032, -0.0558,  0.0140],
          [-0.0136, -0.0585, -0.0521,  0.0039, -0.0569],
          [ 0.1941, -0.0411,  0.0510, -0.0190, -0.1193],
          [-0.0230, -0.1750, -0.0455,  0.1837, -0.0652],
          [-0.0184,  0.1336, -0.0893,  0.0563,  0.1299]]],


        [[[ 0.0538, -0.0281, -0.0299, -0.0359, -0.1776],
          [ 0.0832, -0.0700,  0.1188,  0.0014, -0.1466],
          [-0.0032,  0.1386, -0.1173,  0.0715,  0.0632],
          [ 0.0994,  0.0571, -0.0442, -0.1151,  0.1601],
          [ 0.0817, -0.1822, -0.0610, -0.0254, -0.1065]]],


        [[[ 0.0501,  0.1214,  0.0904,  0.0520,  0.0958],
          [ 0.0218,  0.1796, -0.1540, -0.0337,  0.1694],
          [ 0.0393,  0.0115, -0.1027,  0.1924, -0.0563],
          [ 0.0520, -0.1809, -0.1296,  0.1658, -0.1715],
          [ 0.1849, -0.0940,  0.1015,  0.0133, -0.0957]]],


        [[[ 0.1463,  0.0280, -0.0731,  0.0677,  0.1113],
          [-0.1679, -0.1710,  0.1989,  0.1669,  0.0066

In [52]:
for buf in model.buffers():
    print(buf)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], device='cuda:0')


In [54]:
for child in model.children():
    print(child)

Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
Conv2d(20, 20, kernel_size=(5, 5), stride=(1, 1))
Conv2d(3, 6, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))


In [55]:
for modul in model.modules():
    print(modul)

Model(
  (conv1): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(20, 20, kernel_size=(5, 5), stride=(1, 1))
  (layer1): Conv2d(3, 6, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
)
Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
Conv2d(20, 20, kernel_size=(5, 5), stride=(1, 1))
Conv2d(3, 6, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))


In [78]:
model.train()   # mode = True

Model(
  (conv1): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(20, 20, kernel_size=(5, 5), stride=(1, 1))
  (layer1): Conv2d(3, 6, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
)

In [58]:
model.eval()    # mode = False

Model(
  (conv1): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(20, 20, kernel_size=(5, 5), stride=(1, 1))
  (layer1): Conv2d(3, 6, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
)

In [82]:
for name, param in model.named_parameters():
    param.requires_grad_(False)
    print(name, param.requires_grad)


conv1.weight False
conv1.bias False
conv2.weight False
conv2.bias False
layer1.weight False
layer1.bias False


In [89]:
repr(model)

'Model(\n  (conv1): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))\n  (conv2): Conv2d(20, 20, kernel_size=(5, 5), stride=(1, 1))\n  (layer1): Conv2d(3, 6, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))\n)'

In [90]:
dir(model)

['T_destination',
 '__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_backward_hooks',
 '_buffers',
 '_call_impl',
 '_forward_hooks',
 '_forward_pre_hooks',
 '_get_backward_hooks',
 '_get_name',
 '_is_full_backward_hook',
 '_load_from_state_dict',
 '_load_state_dict_pre_hooks',
 '_maybe_warn_non_full_backward_hook',
 '_modules',
 '_named_members',
 '_non_persistent_buffers_set',
 '_parameters',
 '_register_load_state_dict_pre_hook',
 '_register_state_dict_hook',
 '_replicate_for_data_parallel',
 '_save_to_state_dict',
 '_slow_forward',
 '_state_dict_hooks',
 '_version',
 'add_module',
 'apply',
